language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE cryptofyck;' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhost:5432/cryptofyck
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
